### ISSUE TITLE
JavaScript isn't working on new Version of SparkAR (v110.0.0.13.236)

### ISSUE THREAD

**Issue by DonKDev** [jordyhenry/PlaneTracker.trackingMode#2]
Since SparkAR got updated this Error appears:

ERROR: undefined is not a function
  {
     "line": 6
     "column": 37
     "sourceURL": "script.js"
  }
